### ISSUE TITLE
A new folder `~` is created under home directory

### ISSUE THREAD

**Issue by blahgeek** [qvacua/vimr#674] opened 2018-08-25 07:40 UTC
## Steps to reproduce

- Download SNAPSHOT-293
- Use it to edit some random file
- Look at your home folder

**Comment by qvacua** [comment] 2018-10-23 12:28
I'll have a look at it.

**Comment by Guzzii** [comment] 2019-03-02 01:41
I wanted to delete the folder '~' in terminal, and ended up 20% of my $HOME directory. 😥

**Comment by qvacua** [comment] 2019-03-06 09:34
@Guzzii OMG, I am very sorry to hear that. I only hope that you had Time Machine... Does this also happen with the newest snapshot?

**Comment by Guzzii** [comment] 2019-03-06 21:03
Thanks for the reply @qvacua. Fortunately, I had time machine backup, so it is not a huge deal. I feel like it #710 and this issue are correlated. After rebooting the machine, VimR is able to load shell and env, and no longer creates `~` directory for me.

**Comment by qvacua** [comment] 2019-03-07 06:08
Since I cannot reproduce this issue and it does not seem to occur anymore, I'm closing this issue for now. Please feel free to re-open or create a new issue when this happens again.

**Closed by qvacua** 2019-03-07 06:08 UTC
