### ISSUE TITLE
E1502: Lua failed to grow stack to 4001

### ISSUE THREAD

**Issue by bogdan** [qvacua/vimr#1049] opened 2024-01-19 11:50 UTC
Getting the following error sometimes when opening a file. No side effects of this problem though other than noise.
Reproducible with any file type, but not reproducible using nvim in console.

![image](https://github.com/qvacua/vimr/assets/122436/2bf140a6-fe23-4bad-9e2b-aea1147832b2)

Let me know if there is any way to debug it or provide more information.

**Comment by blentz** [comment] 2024-01-24 17:25
Duplicate of #1044

**Closed** 2024-01-24 17:34 UTC
