### ISSUE TITLE
Application title is difficult to read on a dark titlebar

### ISSUE THREAD

**Issue by s0ph0s-2** [qvacua/vimr#496] opened 2017-07-28 21:33 UTC
I really quite like the new feature were VimR changes its color scheme to match Neovim's. However, I think there's a small bug with it. This feature also sets the title bar color to match as well. It does not lighten the title bar text to make it readable. Below are two screenshots, one of VimR and the other of iTerm2. Here, iTerm2 (bottom) lightens the color of the text to make it readable on a dark background:
![vimr-titlebar-active](https://user-images.githubusercontent.com/20545101/28736943-4a957bec-73ba-11e7-9633-cf7839795261.png)
![iterm2-titlebar-active](https://user-images.githubusercontent.com/20545101/28736948-50aed46a-73ba-11e7-9351-3523719d2c77.png)

Also, while you're tweaking the colors of things in the titlebar, could you also darken the inactive window button circles? They're quite bright currently, as compared to iTerm2's inactive buttons (again, pictured below):
![vimr-titlebar-inactive](https://user-images.githubusercontent.com/20545101/28736989-8494b754-73ba-11e7-833f-dc49281ab2b1.png)
![iterm2-titlebar-inactive](https://user-images.githubusercontent.com/20545101/28736996-8b5164c0-73ba-11e7-880d-10bbfa876b8f.png)

**Comment by tonysyu** [comment] 2017-08-03 21:12
+1
I noticed this issue today. On my screen it's even harder to read than the screenshots. That makes it quite difficult to work with multiple Vimr windows.

**Comment by qvacua** [comment] 2017-08-12 08:56
This is a duplicate of #485. Please follow that issue. Closing...

**Closed by qvacua** 2017-08-12 08:56 UTC
