### ISSUE TITLE
vimr no longer reads ~/.config/nvim/init.vim

### ISSUE THREAD

**Issue by telemachus** [qvacua/vimr#337] opened 2016-11-12 14:06 UTC
OS X: 10.12.1
vimr: Version 0.11.0-SNAPSHOT-20161111.2237 (124)

On start, vimr no longer seems to read (or respect) the settings I have in `~/.config/nvim/init.vim` (for example, my colorscheme is not chosen, line numbers are not set, etc.). In addition, if I try to manually load the colorscheme I want with `:colorscheme github`, I get the error, "E185: Cannot find the color scheme 'github'". (I don't have these problems when using neovim in the terminal.)

**Comment by qvacua** [comment] 2016-11-12 14:29
Does it also happen with https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.11.0-SNAPSHOT-20161111.1436-123 ?

**Comment by telemachus** [comment] 2016-11-12 15:01
Yes, that pre-release has the same problem.

+ [v0.10.1-122](https://github.com/qvacua/vimr/releases/tag/v0.10.1-122) is fine.
+ [v0.11.0-SNAPSHOT-20161109.2136-121](https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.11.0-SNAPSHOT-20161109.2136-121) is the most recent snapshot that is also ok.

**Comment by qvacua** [comment] 2016-11-12 15:45
Hm, that's very strange, I'll look into it.

**Comment by wookayin** [comment] 2016-11-12 15:53
For me, I am using v0.11.0-SNAPSHOT-20161111.2237 and `init.vim` reads and is applied well. Possibly an environment issue?

**Comment by qvacua** [comment] 2016-11-12 15:56
Well, from 121/122 to 123 I added `LANG="en_US.UTF-8"` to the environment when launching the Neovim subprocess via `$SHELL`. (And something when doing `Cmd-V` which most probably does not interfere with `init.vim`.) @wookayin which macOS version are you using? I'm using 10.11.6 and `init.vim` is read fine. Maybe it's a 10.12-thing?

**Comment by telemachus** [comment] 2016-11-12 16:08
For what it's worth, `LANG` is already set to `en_US.UTF-8" in my environment. I can't quite see how setting it again would hurt anything.

(That said, do you really want to set all users' environment to `en_US`? Won't that affect, e.g. money or date handling in ways that British or German users might not want?)

**Comment by qvacua** [comment] 2016-11-12 16:24
Yes, I also don't know how setting it (again) can do some harm.

Hm... I haven't considered it that far... I just wanted that non-ASCII characters are `Cmd-C`ed correctly. Does Neovim get affected by the `LANG` setting? 😶

**Comment by telemachus** [comment] 2016-11-12 16:28
> Does Neovim get affected by the LANG setting? 😶

I'm not entirely sure. I would have guessed yes, but maybe not. However, even if Neovim itself is not affected, what about commands run using `!`, e.g. `:r !date`?

**Comment by qvacua** [comment] 2016-11-13 08:55
I built a version based on 125 without the `LANG`-setting. @telemachus could you try it? http://taewon.de/vimr-test.tar.bz2

**Comment by timhatch** [comment] 2016-11-13 12:22
-122 is the last one that works for me. I'm on OSX 10.11.6 also. 
I'll re-download the other recent releases and check which also exhibit this problem on my machine.

**Comment by telemachus** [comment] 2016-11-13 12:43
@qvacua That test version works for me. I'll use that for now until you sort out what the larger issue is. Thanks!

**Comment by qvacua** [comment] 2016-11-13 13:33
Hm... So it really is that `LANG`-setting... Very strange...

**Comment by timhatch** [comment] 2016-11-13 13:41
The test version picks up the settings in init.vim for me also
-125 was also creating a folder named "~" in the folder containing whichever file I was opening on launch. Hadn't noted that behaviour on any earlier version

**Comment by qvacua** [comment] 2016-11-13 13:54
I could reproduce the behavior on a different machine running 10.12. I'm going to experiment a bit and if I cannot fix it today, I'll build a snapshot without the `LANG`-setting.

**Comment by qvacua** [comment] 2016-11-13 14:15
Try https://github.com/qvacua/vimr/releases/tag/snapshot%2Fv0.11.0-SNAPSHOT-20161113.1502-126. I don't know why exactly, but setting `LANG` a bit later and somewhere else worked at least on my 10.12 machine...

**Comment by timhatch** [comment] 2016-11-13 14:33
Yes, seems fine. 
- Picking up my init.vim setting.
- No new folder created in the working directory

Common plugins working, so no obvious side-effects

**Comment by telemachus** [comment] 2016-11-13 14:59
Yes, this works well for me too. Thanks.

I'll leave this open in case you want to check anything else, but as far as I'm concerned, you can close this report whenever you like.

**Comment by qvacua** [comment] 2016-11-13 16:46
Closing, reopen if the problem pops up again.

**Closed by qvacua** 2016-11-13 16:46 UTC
Labels: bug

**Comment by diedummydie** [comment] 2018-11-07 23:59
This issue has returned with macOS Mohave 10.14 Beta and Snapshot 293. 

If I issue the `:source ~/.config/nvim/init.vim` command manually, then it loads. In Terminal.app, nvim loads the config correctly. I also tried the old "v0.11.0-SNAPSHOT-20161113.1502-126" here, and that does work correctly; that old snapshot does load my init.vim.

**Comment by udp** [comment] 2019-03-29 17:21
I also have the problem of VimR not finding init.vim.

`:healthcheck` shows:

<img width="587" alt="Screen Shot 2019-03-29 at 10 19 17" src="https://user-images.githubusercontent.com/454895/55250735-1d874400-520c-11e9-9732-0b00a52a6261.png">

but the file is definitely there and can be loaded manually with `:source`.

	LANG="en_US.UTF-8"
	LC_COLLATE="en_US.UTF-8"
	LC_CTYPE="en_US.UTF-8"
	LC_MESSAGES="en_US.UTF-8"
	LC_MONETARY="en_US.UTF-8"
	LC_NUMERIC="en_US.UTF-8"
	LC_TIME="en_US.UTF-8"
	LC_ALL=

**Comment by iamcco** [comment] 2019-09-20 15:46
latest version have the same issue

**Comment by hcoona** [comment] 2019-10-24 05:35
reproduce it as well

**Comment by wookayin** [comment] 2019-10-24 07:48
I am using the latest version (v0.28.0-328) and have no issues. What does the `$HOME` variable point to?

**Comment by hcoona** [comment] 2019-10-24 14:46
> 
> 
> I am using the latest version (v0.28.0-328) and have no issues. What does the `$HOME` variable point to?

$HOME = /Users/shuaiz

**Comment by Furkanzmc** [comment] 2020-02-20 14:18
This was closed but I can still reproduce this on macOS 10.4 and VimR Version 0.32.0 (344).
If I run VimR with sudo, the `init.vim` file is sourced but otherwise it's not. And I get the same result as James does.

**Comment by naktinis** [comment] 2020-07-29 15:58
Setting `HOME` variable and running VimR with `--cur-env` seems to have helped me. Of course, this still seems like something that could be fixed on VimR side, because `nvim` runs without problems or extra arguments.
