### ISSUE TITLE
"Toggle File Browser" keyboard shortcut and menu item do not work

### ISSUE THREAD

**Issue by adamalbrecht** [qvacua/vimr#346] opened 2016-11-15 15:57 UTC
Nothing happens when I click Tools --> Toggle File Browser.

Likewise, when I hit cmd-1, nothing happens.

But when I click Tools --> Toggle All Tools (or hit cmd-\\), then it works

I'm using VimR 0.10.2 (127)

**Comment by qvacua** [comment] 2016-11-15 16:51
* the file browser does not have the focus
    * `Cmd-1` focuses the file browser.
    * `Cmd-1` again, then the file browser is hidden

If the file browser has the focus, it's hidden directly. Yes, the menu item's text is confusing... That should be improved...

**Comment by qvacua** [comment] 2017-06-30 20:23
Closing... Please re-open when the issue is still relevant.

**Closed by qvacua** 2017-06-30 20:23 UTC

**Comment by nabn** [comment] 2020-05-12 05:04
Been figuring out for months why this wasn't working. 
While it's nice to have a workaround, IMO Cmd-1 should toggle the file browser if I'm in the editor for example.
