### ISSUE TITLE
Support for mapping of CMD and META keys?

### ISSUE THREAD

**Issue by neektza** [qvacua/vimr#314] opened 2016-10-26 15:06 UTC
Does VimR support mapping the CMD and META keys?

Related discussion (issues/pulls) in the neovim repo:
Feature request for mapping the CMD key: https://github.com/neovim/neovim/issues/2190
Pull request where support for mapping the CMD key was added to neovim: https://github.com/neovim/neovim/pull/4317

Also, when trying to map the META key, for example `<M-1> 1gt` to change the tab, the command works in terminal neovim, but not with VimR. Am I doing something wrong?

**Comment by qvacua** [comment] 2016-10-27 17:58
I think the problem is that many `CMD-{SOME_KEYs}` are menu item shortcuts. We need a more thorough solution like customizable menu item shortcuts like the old VimR with MacVim backend had. That would require some time to implement. Btw: Cmd-1 is mapped to "Open file browser" (or focus it when the focus is elsewhere).

**Comment by p0deje** [comment] 2017-01-06 11:59
What about supporting Option key as Meta? I know that it works with Neovim in iTerm2 and Neovim.app, so I guess it can be done in VimR as well (not sure about Cmd shortcuts).

**Comment by jrolfs** [comment] 2017-01-23 00:23
I'm also curious about "meta" key support. Neither `<A-[x]>` or `<M-[x]>` mappings seem to work for me.

**Comment by jrolfs** [comment] 2017-01-23 00:32
For the record, said mappings do work when running Neovim in iTerm with the ⌥ [mapped "correctly"](http://stackoverflow.com/questions/196357/making-iterm-to-translate-meta-key-in-the-same-way-as-in-other-oses#comment1042379_438892).

**Comment by env0der** [comment] 2017-04-21 20:02
I would also like to have an ability to map "meta" key

**Comment by SolaWing** [comment] 2017-08-31 01:15
What's the progress of this? Or is there any plan to support this?

**Comment by trws** [comment] 2017-09-11 19:08
Perhaps worth a cross-reference to where neovim.app added this: rogual/neovim-dot-app/pull/250

**Comment by eugenk** [comment] 2017-12-14 14:39
I have successfully mapped the CMD key in vimr like this:
```vim
if has("gui_vimr")
  nnoremap <D-h>  :bfirst<CR>
  nnoremap <D-k>  :bnext<CR>
  nnoremap <D-j>  :bprevious<CR>
  nnoremap <D-l>  :blast<CR>
  nnoremap <D-e>  :e<Space>
  nnoremap <D-E>  :enew<CR>
endif
```

**Comment by trws** [comment] 2017-12-15 03:37
Yeah, cmd is fine, it's alt/option or "meta" that is not fine.

**Comment by eugenk** [comment] 2017-12-15 08:48
Ah, sorry, I misunderstood.

**Comment by mrinterweb** [comment] 2018-01-08 04:24
@eugenk thanks for that example of your mappings. That helped me get the MacOS tab switching commands to work, as they do in MacVim and other apps. 

```
if has("gui_vimr")
  nnoremap <silent><D-S-{> gT
  nnoremap <silent><D-S-}> gt
endif
```

**Comment by CodeMonkeyMike** [comment] 2018-02-09 17:35
I have the issue of being unable to use Alt and Meta commands in the :terminal, I think this may be something I would be able to use as well. Thanks

**Comment by qvacua** [comment] 2018-04-07 12:16
The new [snapshot](https://github.com/qvacua/vimr/releases) has two new options for left or/and right Option key as Meta. I'll try to implement a (simple) general shortcut management soon.

**Comment by qvacua** [comment] 2019-02-28 11:18
You can change all key shortcuts of menu items in the latest snapshot: https://github.com/qvacua/vimr/releases

That means you can delete for example the `Command-1` for "Toggle File Browser" menu item and use `Command-1` for something else.

**Comment by qvacua** [comment] 2019-02-28 13:34
Closing... If it does not work, then please re-open.

**Closed by qvacua** 2019-02-28 13:34 UTC
Labels: in progress

**Comment by risentveber** [comment] 2019-07-26 09:48
@qvacua Mapping with CMD with a mouse click doesn't work
For example:
```
noremap <D-RightMouse> :GoReferrers<CR>
```
do nothing, but if I use `Ctrl` instead it works:
```
noremap <C-RightMouse> :GoReferrers<CR>
```

**Comment by mskar** [comment] 2020-10-23 22:05
Does anyone know the terminal escape code for `<D-CR>`?
I found all the other `<CR>` combo escape codes:

| KeyCombo       | EscapeCode |
|----------------|------------|
| \<S-CR\>       | [13;2u     |
| \<M-CR\>       | [13;3u     |
| \<M-S-CR\>     | [13;4u     |
| \<C-CR\>       | [13;5u     |
| \<C-S-CR\>     | [13;6u     |
| \<M-C-CR\>     | [13;7u     |
| \<M-C-S-CR\>   | [13;8u     |
