### ISSUE TITLE
VimR should register itself as an editor for various source-code and plain-text formats

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [qvacua/vimr#577] opened 2017-12-04 00:27 UTC
When attempting to select an editor for various file types, MacVim, Atom, et all show up as options; this is because they register themselves as an editor for those types:

<img width="780" alt="screen shot 2017-12-03 at 18 19 42" src="https://user-images.githubusercontent.com/200/33531741-ed581e60-d856-11e7-97e5-b1a77a54dcb0.png">

VimR, however, at the moment, only registers itself for `vimr:` URLs and the singular `public.data` UTI:

<img width="780" alt="screen shot 2017-12-03 at 18 19 45" src="https://user-images.githubusercontent.com/200/33531746-fcbfe18a-d856-11e7-9974-a5dae3572329.png">

Although VimR can thus be configured as the editor for single files (by right-click, “Open With” > “Other …”, and checking “Always open with”), and for a single file category at a time (with tools like [RCDefaultApp](http://www.rubicode.com/Software/RCDefaultApp/)), it's impossible to configure VimR as the default text-editor for an *entire category* of files, such as all text files, as can be done with an app configured as MacVim is.

<img width="665" alt="screen shot 2017-12-03 at 18 24 45" src="https://user-images.githubusercontent.com/200/33531787-b2bf0b00-d857-11e7-9b1c-550ae8683f0f.png">

(Also, for users who don't know about RCDefaultApp or similar, it may be worth-while to include a “Re-configure VimR as the default editor for all source-code file-types” button in the configuration panel or one of the menus! That may need a different Issue, though.)

**Comment by qvacua** [comment] 2018-01-14 09:52
This is duplicate of #402.

**Closed by qvacua** 2018-01-14 09:52 UTC
Labels: duplicate
