### ISSUE TITLE
airline render different?

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [qvacua/vimr#407] opened 2017-03-05 14:35 UTC
it's not a bug but i'm curious on it, why they are different in terminal and in VimR?
<img width="417" alt="screen shot 2017-03-05 at 10 32 33 pm" src="https://cloud.githubusercontent.com/assets/2133400/23588121/aae1aaf4-01f3-11e7-83d5-2aa9218c23f4.png">
got the differences? airline in terminal neovim has max line number and the LN sign, while VimR below only has current line number, not only in vimR,i tried neovim-dot-app, it has the same problem.

**Comment by qvacua** [comment] 2017-03-29 16:40
I don't know...

**Comment by FinallyFinancialFreedom** [comment] 2017-07-02 16:26
hi, @qvacua  i updated to the newest version and i  find out that the airline renderd in vimr is the same as neovim in terminal, it's great. what did you do?

**Comment by qvacua** [comment] 2017-07-02 16:51
Hm... I don't know... 😬 Well, glad to here that the issue is gone... 😀 Closing...

**Closed by qvacua** 2017-07-02 16:51 UTC
