### ISSUE TITLE
TERM is not set

### ISSUE THREAD

**Issue by romaninsh** [qvacua/vimr#356] opened 2016-11-29 18:23 UTC
Probably not a huge deal, but if you type

``` 
:CheckHealth
```

It complains about TERM variable not being set:

```
## terminfo
  - ERROR: command failed: infocmp -L
    infocmp: environment variable TERM not set
```

**Comment by qvacua** [comment] 2016-11-29 20:50
😆 This is a duplicate of #331 and #348 (see especially https://github.com/qvacua/vimr/issues/348#issuecomment-263370259). Closing...

**Closed by qvacua** 2016-11-29 20:50 UTC
