### ISSUE TITLE
Environment variable `TERM` not set

### ISSUE THREAD

**Issue by telemachus** [qvacua/vimr#348] opened 2016-11-21 15:26 UTC
Running `:CheckHealth` shows the following:

    ## terminfo
      - ERROR: command failed: infocmp -L
        infocmp: environment variable TERM not set

I'm assuming that this has to do with how `vimr` sets up the environment, because `:CheckHealth` with `nvim` in the terminal shows this:

     ## terminfo                                                                 
       - INFO: key_backspace terminfo entry: key_backspace=\177,

This may not matter. That is, I haven't run into a concrete problem that this causes, but in theory it might lead to issues when running `!` commands from `vimr`. In any case, I noticed it and thought I would mention it for future reference.

**Comment by qvacua** [comment] 2016-11-23 21:54
I think that this is a duplicate of GH-331: See https://github.com/qvacua/vimr/issues/331#issuecomment-258941061

**Comment by justinmk** [comment] 2016-11-28 19:33
Actually, this is arguably a CheckHealth bug. It should skip that check if `TERM` is empty (better: if TUI isn't running).

**Comment by qvacua** [comment] 2016-11-29 17:31
OK. Closing... (probably VimR is the only GUI having this issue?) :)

**Closed by qvacua** 2016-11-29 17:31 UTC
Labels: duplicate
