### ISSUE TITLE
Command line option -u for using a different vimrc file

### ISSUE THREAD

**Issue by iovis9** [qvacua/vimr#421] opened 2017-04-03 15:27 UTC
Both Neovim and vim support this feature. Aside from helping people like me who sometimes use different `.vimrc` files (I have a minimal version for working with large files), I think it would help a lot for debugging simple things: like when people use `vim -u NONE` to rule out problems with your configuration and detect bugs.

**Comment by kwkelly** [comment] 2017-05-28 20:06
I'm going to second this. I'm trying to dissect the cause of some slow scrolling in normal mode in vimr, and just seeing if the issue exists without loading a .vimrc or init.vim would be helpful.

**Comment by qvacua** [comment] 2017-06-12 19:53
The slow scrolling should be fixed in the latest release; or at least it's now fast enough on my machine.  😬
However, with GH-302 it will be possible to use any option of `nvim` with the `vimr` CLI tool. Stay tuned :)

**Closed** 2017-06-13 05:38 UTC
Labels: enhancement
