### ISSUE TITLE
copy paste to VimR at head of line bug

### ISSUE THREAD

**Issue by FinallyFinancialFreedom** [qvacua/vimr#603] opened 2018-01-15 03:41 UTC
at first , in VimR, the first line is `321`, and VimR in INSERT MODE, and the cursor stand at the head of the first line.
when i copy a `4` letter and paste to VimR, i expect a `4321` result, but i get `3421` result.
if the cursor stands at other position except head of line, the result is ok.

**Comment by minusf** [comment] 2018-01-17 08:13
i confirm this bug. pressing cmd-v in column position 0 will paste starting at position 1:

```123
|123                     <-- paste clipboard content '4'
1423                     <-- expected output is 4123
```

**Comment by minusf** [comment] 2018-02-19 21:25
this is a quite annoying bug, and probably not that hard to fix.  seems like an off-by-one.  could you have a look please? :}

**Comment by EarthCitizen** [comment] 2018-07-15 05:48
Bug still present in 0.24.0. The problem does not exist in NeoVim 0.3.0 from the terminal.

**Comment by qvacua** [comment] 2018-07-15 20:07
For whatever reason I thought that I've already fixed this... Now it should be fixed: @FinallyFinancialFreedom @minusf @EarthCitizen Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F285

**Closed by qvacua** 2018-07-15 20:07 UTC
Labels: bug

**Comment by qvacua** [comment] 2018-07-16 16:38
The last snapshot broke pasting at column > 0. Please try https://github.com/qvacua/vimr/releases/tag/snapshot%2F286

**Comment by EarthCitizen** [comment] 2018-07-16 18:40
Seems that my work laptop is locked down. I am unable to run this snapshot due to it not being signed.

**Comment by minusf** [comment] 2018-07-16 21:32
it seems to fix the original issue.  if i keep my fingers on cmd-v though, i get:

```
|123    <-- paste "4" at column 0 many times
44"+p"+p"+p"+p"+p"+p"+p"+p"+p"+p"+p"+p"+p"+p"+p44123
```

**Comment by qvacua** [comment] 2018-07-23 17:03
@EarthCitizen I don't know what went wrong, but code signing was indeed somehow broken. Please try the latest snapshot: https://github.com/qvacua/vimr/releases/tag/snapshot%2F290

@minusf Hm... Let's see how to fix that...

**Comment by EarthCitizen** [comment] 2018-07-23 21:17
@qvacua Signing is correct now.

For insert mode, it seems to have fixed the problem. If I have:
`asdf`
and `VimR` in the clipboard
and I am in insert mode
and I have `|asdf`
then `Cmd-v` gives me
`VimR|asdf`

For normal mode, if I have:
`asdf`
and the cursor is on `a`
and I type `Cmd-v`
then I get `aVimRsdf`

This may be the intended behavior for normal mode, but reporting my findings just in case.
