### ISSUE TITLE
Shift-tab doesn't work in vimr

### ISSUE THREAD

**Issue by pencilcheck** [qvacua/vimr#447] opened 2017-05-12 07:48 UTC
```
vnoremap <Tab> >gv|
vnoremap <S-Tab> <gv
nnoremap > >>_
nnoremap < <<_
```

In vimr, the first line works but second line moves the cursor up one line instead of decrease indentation like it should be in nvim.

**Comment by mkhl** [comment] 2017-05-12 16:05
I’m seeing this as well. VimR seems to see the key combination as <kbd>C-y</kbd> instead of <kbd>S-Tab</kbd> (checked using <kbd>C-v</kbd>).

**Comment by mkhl** [comment] 2017-05-16 18:52
Probably a duplicate of #403, except the problem ist not limited to command mode.

**Closed** 2017-05-17 20:12 UTC
