### ISSUE TITLE
Window title color issue

### ISSUE THREAD

**Issue by osenvosem** [qvacua/vimr#502] opened 2017-08-04 18:00 UTC
MacOS 10.12.6

![screen shot 2017-08-04 at 20 58 21](https://user-images.githubusercontent.com/6762673/28980778-c6de4a92-7957-11e7-9e9c-94f14da74a20.png)

**Comment by tonysyu** [comment] 2017-08-08 04:02
This is a duplicate of #496

**Closed** 2017-08-08 04:03 UTC
