### ISSUE TITLE
Switching out and back to vimr while using denite.vim would freeze

### ISSUE THREAD

**Issue by evanslify** [qvacua/vimr#634] opened 2018-04-04 08:26 UTC
Steps to produce:

1. open VimR
2. open denite (`:Denite buffer`)
3. command+tab or just switch to other window back and forth for a couple times
4. VimR would freeze

I'm using neovim v0.2.2, vimr 271, latest denite.vim

**Comment by qvacua** [comment] 2018-06-22 08:19
Does this also happen with the newest snapshot? If so, I'll have a look at it.

**Comment by evanslify** [comment] 2018-06-24 05:58
Just upgraded to latest snapshot, I will check it out and get back to you.

**Comment by evanslify** [comment] 2018-07-16 12:56
@qvacua I can still reproduce with 282. Should I try with latest snapshot?

**Comment by qvacua** [comment] 2018-07-16 20:02
If it happens on 282, it will probably happen on the latest snapshot. I don't yet understand what's happening...

**Comment by qvacua** [comment] 2018-07-22 09:37
On the latest snapshot 289 I could not reproduce it... Could you please try it?

**Comment by evanslify** [comment] 2018-07-22 14:48
Weird. I just upgraded to neovim 0.3.1 from 0.3.0 and using snapspot-289, I
could not reproduce this at the moment. Will report if I can find out a way
to reproduce this reliably.

**Comment by qvacua** [comment] 2018-07-23 05:38
I'll close this issue for the time being. Please re-open when it occurs again. BTW: VimR includes its own neovim (and the newest snapshot has 0.3.1).

**Closed by qvacua** 2018-07-23 05:38 UTC
