### ISSUE TITLE
Add option to quit after last window closes

### ISSUE THREAD

**Issue by goerz** [qvacua/vimr#429] opened 2017-04-24 20:21 UTC
I'm have a KeyboardMaestro Macro that copies text from the current app, writes it to a temporary file, opens that file in an editor, waits for the editor to exit, reads the modified content of the temporary file, and pastes that back into the original app. For this to work, the text editor must exit completely. Currently, in VimR, when I write and close the edited file (`:wq`), VimR stays active (with no open windows), and I have to hit `⌘Q` to quit the app.

It would be great if you could add an option "Quit VimR after last window closes" (behaving like the corresponding option in MacVim).

**Comment by qvacua** [comment] 2017-04-25 04:52
Duplicate of GH-326, closing.

**Closed by qvacua** 2017-04-25 04:52 UTC
Labels: duplicate
