### ISSUE TITLE
Command line invoking of diff (-d flag)

### ISSUE THREAD

**Issue by msravi** [qvacua/vimr#453] opened 2017-05-17 04:49 UTC
vim, gvim, and nvim allow invoking of the respective editor in diff mode:

```
vim -d file1.txt file2.txt
gvim -d file1.txt file2.txt
nvim -d file1.txt file2.txt
```

However, it appears that vimr is missing the `-d` flag. This is essential for using vimr as the difftool in git, and is very useful for quickly seeing differences visually from the command line. Request you to please add in future releases.

Thanks!

**Comment by qvacua** [comment] 2017-05-17 20:14
Duplicate of GH-302, closing this one.

**Closed by qvacua** 2017-05-17 20:14 UTC
Labels: duplicate
