### ISSUE TITLE
crash when vimrc have echom

### ISSUE THREAD

**Issue by xiehuc** [qvacua/vimr#569] opened 2017-11-25 04:01 UTC
```
echo "echom 'hello'" > /tmp/vimrc
vimr --nvim -u /tmp/vimrc
```

reproduce it

**Comment by ELLIOTTCABLE** [comment] 2017-11-28 22:52
Looks like a duplicate of #553 (see [my comment](https://github.com/qvacua/vimr/issues/553#issuecomment-347690154)!)

**Comment by qvacua** [comment] 2018-01-13 13:58
@xiehuc do you still have the problem?

**Comment by xiehuc** [comment] 2018-01-14 02:13
use newest version never crash，thank you👍👍

发自我的 iPad

**Closed** 2018-01-14 02:13 UTC
