### ISSUE TITLE
Changing font-size and font-face is not permanent

### ISSUE THREAD

**Issue by aaron-goshine** [qvacua/vimr#279] opened 2016-09-15 10:21 UTC
Changing font-size and font-face is not permanent, after restart it's reverted

**Comment by qvacua** [comment] 2016-09-15 20:15
Which version are you using? I cannot reproduce it with the latest snapshot.

**Comment by qvacua** [comment] 2016-10-05 20:34
Closing... Please reopen if the problem persists.

**Closed by qvacua** 2016-10-05 20:34 UTC
