### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by kammerdienerb** [qvacua/vimr#616] opened 2018-03-01 04:43 UTC
VimR snapshot 265 crashes when I start the app.

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSNull advancementForGlyph:]: unrecognized selector sent to instance 0x7fffaf6e2de0'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff555a454b __exceptionPreprocess + 171
1   libobjc.A.dylib                     0x00007fff7d072c76 objc_exception_throw + 48
2   CoreFoundation                      0x00007fff5563d024 -[NSObject(NSObject) doesNotRecognizeSelector:] + 132
3   CoreFoundation                      0x00007fff5551aa90 ___forwarding___ + 1456
4   CoreFoundation                      0x00007fff5551a458 _CF_forwarding_prep_0 + 120
5   UIFoundation                        0x00007fff79a77be2 __NSStringDrawingEngine + 6421
6   UIFoundation                        0x00007fff79ac478a -[NSAttributedString(NSStringDrawing) drawInRect:] + 161
7   CocoaFontAwesome                    0x000000010879f7a9 swift_rt_swift_getInitializedObjCClass + 2441
8   CocoaFontAwesome                    0x000000010879bef8 -[NSImage(UKRemoveTransparentAreas) trimming] + 1816
9   VimR                                0x00000001083b0a6a _T04VimR12InnerToolBarC8addViews021_7B68BF9A8120034F62B2H9BDF41B3D4LLyyF + 458
10  VimR                                0x00000001083af97f _T04VimR12InnerToolBarCAcA06CustomcD0CSg13customToolbar_SaySo10NSMenuItemCG0F9MenuItemstcfc + 991
11  VimR                                0x00000001083d5ead _T04VimR13WorkspaceToolCA2C6ConfigVcfc + 525
12  VimR                                0x0000000108534c43 _T04VimR10MainWindowCAC7RxSwift10ObservableCyAC5StateVG6source_AA13ActionEmitterC7emitterAH5statetcfc + 4275
13  VimR                                0x0000000108437bd0 _T04VimR6UiRootC13newMainWindow33_8ECA61C70B364ED2D49DC97051709EC7LLAA0eF0CAG5StateV4with_tFTf4gn_n + 4256
14  VimR                                0x000000010843aa1d _T04VimR6UiRootCAC7RxSwift10ObservableCyAA8AppStateVG6source_AA13ActionEmitterC7emitterAH5statetcfcyAHcfU_Tf4gn_n + 5069
15  VimR                                0x000000010842d61c _T04VimR6UiRootCAC7RxSwift10ObservableCyAA8AppStateVG6source_AA13ActionEmitterC7emitterAH5statetcfcyAHcfU_ + 1116
16  VimR                                0x00000001084361f9 _T04VimR6UiRootCAC7RxSwift10ObservableCyAA8AppStateVG6source_AA13ActionEmitterC7emitterAH5statetcfcyAHcfU_TA + 41
17  VimR                                0x0000000108526066 _T04VimR8AppStateVIxx_ACIxi_TR + 694
18  VimR                                0x0000000108436253 _T04VimR8AppStateVIxx_ACIxi_TRTA + 51
19  RxSwift                             0x000000010881039c globalinit_33_C23F0B6AB9DDC216E1CAAB51FEEC20B7_func6 + 908
20  RxSwift                             0x000000010880ff89 globalinit_33_AB29D84AF07E52B00E928967DD5A9DD7_func4 + 20201
21  RxSwift                             0x000000010881014c globalinit_33_C23F0B6AB9DDC216E1CAAB51FEEC20B7_func6 + 316
22  RxSwift                             0x0000000108829bf7 swift_rt_swift_unpin + 6791
23  RxSwift                             0x0000000108817213 __swift_memmove_array8_8 + 5219
24  RxSwift                             0x00000001088173fa __swift_memmove_array8_8 + 5706
25  RxSwift                             0x00000001088a4461 globalinit_33_932BAA1B71BEB3FA14752E35DCF55AA2_func20 + 38913
26  RxSwift                             0x00000001088a4f09 create_generic_metadata_ObserveOnTm + 169
27  RxSwift                             0x00000001088a4fbc create_generic_metadata_ObserveOnTm + 348
28  RxSwift                             0x000000010880b046 block_destroy_helper + 294
29  RxSwift                             0x000000010880aed0 globalinit_33_E3BC7F891F5DA88E0E2A9C34CB16220E_func3 + 1408
30  RxSwift                             0x00000001087efe20 swift_rt_swift_dynamicCastClass + 18512
31  libdispatch.dylib                   0x00007fff7dc5a64a _dispatch_call_block_and_release + 12
32  libdispatch.dylib                   0x00007fff7dc52e08 _dispatch_client_callout + 8
33  libdispatch.dylib                   0x00007fff7dc5e3e5 _dispatch_main_queue_callback_4CF + 1148
34  CoreFoundation                      0x00007fff5555ce89 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
35  CoreFoundation                      0x00007fff5551f06a __CFRunLoopRun + 2586
36  CoreFoundation                      0x00007fff5551e3c3 CFRunLoopRunSpecific + 483
37  HIToolbox                           0x00007fff5480ad86 RunCurrentEventLoopInMode + 286
38  HIToolbox                           0x00007fff5480aaf6 ReceiveNextEventCommon + 613
39  HIToolbox                           0x00007fff5480a874 _BlockUntilNextEventMatchingListInModeWithFilter + 64
40  AppKit                              0x00007fff52abcc17 _DPSNextEvent + 2085
41  AppKit                              0x00007fff53252f04 -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:] + 3044
42  AppKit                              0x00007fff52ab1a29 -[NSApplication run] + 764
43  AppKit                              0x00007fff52a80c02 NSApplicationMain + 804
44  VimR                                0x000000010839f759 main + 9
45  libdyld.dylib                       0x00007fff7dc8c015 start + 1

**Comment by qvacua** [comment] 2018-03-04 09:50
This is a duplicate of #611. Please track the progress there. Closing

**Closed by qvacua** 2018-03-04 09:50 UTC
